name: "publish"

on:
    push:
        tags:
            - "tchap-*"

# `tauri-action` can also upload app bundles to an existing GitHub release.
# This workflow uses different actions to create and publish the release.
# `tauri-action` will only build and upload the app bundles to the specified release.

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.prepare-release.outputs.id }}

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: get version
        id: version
        run: echo "PACKAGE_VERSION=$(node -p "require('./src-tauri/tauri.conf.json').version")" >> $GITHUB_OUTPUT

      - name: Prepare release
        id: prepare-release
        uses: ncipollo/release-action@v1
        with:
            tag: "tchap-${{ steps.version.outputs.PACKAGE_VERSION }}"
            generateReleaseNotes: true
            token: ${{ secrets.GITHUB_TOKEN }}
            allowUpdates: true


  build-tauri:
    needs: create-release
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        include:
          - platform: "windows-latest"
            args: "--config src-tauri/tauri.conf.prod.json"
    uses: ./.github/workflows/build-tauri.yml
    with:
      platform: ${{ matrix.platform }}
      args : ${{ matrix.args }}
      releaseId: ${{ needs.create-release.outputs.release_id }}
    secrets:
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
