name: "test-on-build"

on: [pull_request]

# This workflow will build your tauri app without uploading it anywhere.

jobs:
  build-tauri:
    strategy:
      fail-fast: true
      matrix:
        include:
          - platform: "windows-latest"
            args: ""
    uses: ./.github/workflows/build-tauri.yml
    with:
      platform: ${{ matrix.platform }}
      args : ${{ matrix.args }}
    secrets:
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}